# Generated by Django 4.1.7 on 2023-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Email", models.CharField(max_length=40)),
                ("Subject", models.CharField(max_length=100)),
                ("Message", models.TextField(max_length=500)),
            ],
        ),
    ]
