version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/mindcare  # Adjust the volume path based on your project structure
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"