# Generated by Django 4.1.7 on 2023-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsmodel",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
