# Generated by Django 4.1.7 on 2023-03-11 12:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=150),
        ),
    ]
