# Generated by Django 4.1.7 on 2023-03-11 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content_alter_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
