# Generated by Django 4.1.7 on 2023-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
