# Generated by Django 4.1.7 on 2023-03-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
