# Generated by Django 4.1.7 on 2023-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_title_alter_blog_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=400),
        ),
    ]
