# Generated by Django 4.1.7 on 2023-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="url",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
